version: '3.8'

services:
  climaxtreme:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./configs:/app/configs
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - SPARK_LOCAL_IP=0.0.0.0
    command: climaxtreme dashboard --host 0.0.0.0

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --notebook-dir=/app/notebooks

volumes:
  data:
  logs:
  models: